### ISSUE TITLE
pywinusb errors

### ISSUE THREAD

**Issue by XSecr3t** [Mati365/pyWinUSB#6]
do not understand for this session, can you help me?

> pywinusb
/usr/local/lib/python3.7/dist-packages/py_winusb-0.2.0.1-py3.7.egg/pywinusb/__main__.py:2: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Gdk
Traceback (most recent call last):
  File "/usr/local/bin/pywinusb", line 11, in <module>
    load_entry_point('py-winusb==0.2.0.1', 'console_scripts', 'pywinusb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/py_winusb-0.2.0.1-py3.7.egg/pywinusb/__main__.py", line 3, in <module>
    from pywinusb.window import AppWindow
  File "/usr/local/lib/python3.7/dist-packages/py_winusb-0.2.0.1-py3.7.egg/pywinusb/window.py", line 4, in <module>
    from pywinusb.creator import USBCreator
  File "/usr/local/lib/python3.7/dist-packages/py_winusb-0.2.0.1-py3.7.egg/pywinusb/creator.py", line 1, in <module>
    import sh, os, re, threading, hashlib, subprocess
ModuleNotFoundError: No module named 'sh'

thank you

**Comment by Mati365** [comment]
Thx! I will check it
